import Foundation

/// Immutable private definitions. A definition follows its creator when the creator is assigned a different
/// block; a tag alone is never sufficient. `standard` holds the merged DCMTK and GDCM private dictionaries
/// (issue #2795); callers may supply their own.
public struct DicomPrivateDictionary: Sendable {
    public struct Entry: Sendable {
        public let group: UInt16
        public let creator: String
        public let offset: UInt8
        public let vr: DicomVR
        public let name: String?

        public init(group: UInt16, creator: String, offset: UInt8, vr: DicomVR, name: String? = nil) {
            self.group = group
            self.creator = creator
            self.offset = offset
            self.vr = vr
            self.name = name
        }
    }

    public enum Failure: Error, Equatable, Sendable {
        case invalidDefinition
        case duplicateDefinition
    }

    private struct Key: Hashable, Sendable {
        let group: UInt16
        let creator: String
        let offset: UInt8
    }

    private let definitions: [Key: (vr: DicomVR, name: String?)]
    public static let empty = Self(definitions: [:])

    /// DCMTK's private.dic merged with GDCM's default private dictionaries, DCMTK first where they disagree
    /// (`Resources/DicomPrivateDictionary.tsv`, regenerated by `Tools/Scripts/generate_private_dictionary.py`).
    public static let standard: Self = {
        guard let url = Bundle.module.url(forResource: "DicomPrivateDictionary", withExtension: "tsv"),
              let text = try? String(contentsOf: url, encoding: .ascii) else { return .empty }
        var definitions: [Key: (vr: DicomVR, name: String?)] = [:]
        for line in text.split(separator: "\n") {
            let fields = line.split(separator: "\t", omittingEmptySubsequences: false)
            guard fields.count == 5, let group = UInt16(fields[0], radix: 16), let offset = UInt8(fields[2], radix: 16),
                  fields[3].utf8.count == 2, let first = fields[3].utf8.first, let last = fields[3].utf8.last,
                  let vr = DicomVR(rawValue: Int(first) << 8 | Int(last)) else { continue }
            let key = Key(group: group, creator: String(fields[1]), offset: offset)
            if definitions[key] == nil { definitions[key] = (vr, fields[4].isEmpty ? nil : String(fields[4])) }
        }
        return Self(definitions: definitions)
    }()

    private init(definitions: [Key: (vr: DicomVR, name: String?)]) { self.definitions = definitions }

    public init(entries: [Entry]) throws {
        var definitions: [Key: (vr: DicomVR, name: String?)] = [:]
        for entry in entries {
            guard entry.group >= 9, entry.group != 0xFFFF, !entry.group.isMultiple(of: 2),
                  !entry.creator.isEmpty, entry.creator.utf8.count <= 64,
                  entry.creator.unicodeScalars.allSatisfy({ (0x20...0x7E).contains($0.value) && $0.value != 0x5C }),
                  entry.creator == entry.creator.trimmingCharacters(in: .whitespaces),
                  ![DicomVR.unknown, .implicitRaw, .QQ, .RT].contains(entry.vr) else {
                throw Failure.invalidDefinition
            }
            let key = Key(group: entry.group, creator: entry.creator, offset: entry.offset)
            guard definitions[key] == nil else { throw Failure.duplicateDefinition }
            definitions[key] = (entry.vr, entry.name)
        }
        self.definitions = definitions
    }

    public func vr(group: UInt16, creator: String, offset: UInt8) -> DicomVR? {
        definitions[Key(group: group, creator: creator, offset: offset)]?.vr
    }

    public func name(group: UInt16, creator: String, offset: UInt8) -> String? {
        definitions[Key(group: group, creator: creator, offset: offset)]?.name
    }

    /// A wire creator uses LO, VM 1 and the default repertoire independently of
    /// Specific Character Set. Empty values do not reserve a private block.
    static func creatorIdentifier(vr: DicomVR, bytes: Data) throws -> String? {
        guard vr == .LO, bytes.count <= 64,
              bytes.allSatisfy({ (0x20...0x7E).contains($0) && $0 != 0x5C }),
              let value = String(data: bytes, encoding: .ascii) else {
            throw DicomDataSetReadResult.Diagnostic.Reason.invalidPrivateCreator
        }
        let identifier = value.trimmingCharacters(in: .whitespaces)
        return identifier.isEmpty ? nil : identifier
    }

    static func isCreatorTag(_ tag: Int) -> Bool {
        let group = (tag >> 16) & 0xFFFF
        return group >= 9 && group != 0xFFFF && !group.isMultiple(of: 2) && (0x10...0xFF).contains(tag & 0xFFFF)
    }
}
