//
//  DicomDeidentificationTable.swift
//
//  PS3.15 Annex E tables (E.1-1 attribute actions, E.3.10-1 safe private attributes) loaded from the
//  generated, versioned resource. The table is data; the de-identifier applies it.
//

import Foundation

/// PS3.15 Table E.1-1 and Table E.3.10-1 for one edition of the Standard.
public struct DicomDeidentificationTable: Sendable {
    /// Action codes of Table E.1-1, verbatim. Compound codes keep both alternatives; the de-identifier
    /// resolves them without dropping a Type 1/2 attribute (see `DicomDeidentificationActionCode.resolved`).
    public enum ActionCode: String, Sendable, Codable, CaseIterable {
        case remove = "X"
        case zero = "Z"
        case dummy = "D"
        case replaceUID = "U"
        case keep = "K"
        case clean = "C"
        case removeOrZero = "X/Z"
        case removeOrDummy = "X/D"
        case zeroOrDummy = "Z/D"
        case removeOrZeroOrDummy = "X/Z/D"
        case removeOrZeroOrUID = "X/Z/U*"
    }

    /// Options of PS3.15 E.2/E.3 that modify the Basic Application Level Confidentiality Profile.
    public enum Option: String, Sendable, Codable, CaseIterable {
        case retainSafePrivate
        case retainUIDs
        case retainDeviceIdentity
        case retainInstitutionIdentity
        case retainPatientCharacteristics
        case retainLongitudinalFullDates
        case retainLongitudinalModifiedDates
        case cleanDescriptors
        case cleanStructuredContent
        case cleanGraphics

        /// PS3.16 CID 7050 code for the option, recorded in De-identification Method Code Sequence.
        public var code: (value: String, meaning: String) {
            switch self {
            case .retainSafePrivate: return ("113111", "Retain Safe Private Option")
            case .retainUIDs: return ("113110", "Retain UIDs Option")
            case .retainDeviceIdentity: return ("113109", "Retain Device Identity Option")
            case .retainInstitutionIdentity: return ("113112", "Retain Institution Identity Option")
            case .retainPatientCharacteristics: return ("113108", "Retain Patient Characteristics Option")
            case .retainLongitudinalFullDates: return ("113106", "Retain Longitudinal Temporal Information Full Dates Option")
            case .retainLongitudinalModifiedDates: return ("113107", "Retain Longitudinal Temporal Information Modified Dates Option")
            case .cleanDescriptors: return ("113105", "Clean Descriptors Option")
            case .cleanStructuredContent: return ("113104", "Clean Structured Content Option")
            case .cleanGraphics: return ("113103", "Clean Graphics Option")
            }
        }
    }

    /// One row of Table E.1-1.
    public struct Entry: Sendable, Equatable {
        public let name: String
        /// Concrete tag, or a masked pattern (`50xxxxxx`, `60xx3000`).
        public let tagPattern: String
        public let basic: ActionCode
        public let options: [Option: ActionCode]
        public let retired: Bool
        public let inStandardIOD: Bool

        let mask: Int
        let value: Int

        /// The action the profile assigns once the enabled options are applied: any enabled option that
        /// keeps wins, otherwise any enabled option that cleans, otherwise the basic action.
        public func action(with enabled: Set<Option>) -> ActionCode {
            let applicable = options.filter { enabled.contains($0.key) }.values
            if applicable.contains(.keep) { return .keep }
            if applicable.contains(.clean) { return .clean }
            return basic
        }
    }

    /// One row of Table E.3.10-1.
    public struct SafePrivateEntry: Sendable, Equatable {
        public let creator: String
        /// `7053xx00`: group, creator block placeholder, element within the block.
        public let elementPattern: String
        public let vr: String
        public let vm: String
        public let meaning: String

        let group: Int
        let elementLow: Int
    }

    public let standard: String
    public let version: String
    public let sourceSHA256: String
    public let entries: [Entry]
    public let safePrivateEntries: [SafePrivateEntry]
    /// Row for private attributes ("(gggg,eeee) where gggg is odd").
    public let privateEntry: Entry?

    private let exact: [Int: Entry]
    private let patterns: [Entry]
    private let safeByGroup: [Int: [SafePrivateEntry]]

    /// The edition shipped with the package (generated by `generate_deidentification_table.py`).
    public static let standard: DicomDeidentificationTable = load()

    /// The Table E.1-1 row for a standard tag (masked rows such as Curve Data and Overlay groups included).
    public func entry(forTag tag: Int) -> Entry? {
        if let entry = exact[tag] { return entry }
        return patterns.first { tag & $0.mask == $0.value }
    }

    /// Whether a private element is listed as safe for the private creator that owns its block.
    public func isSafePrivate(tag: Int, creator: String) -> Bool {
        let group = tag >> 16 & 0xFFFF
        guard group.isMultiple(of: 2) == false, let candidates = safeByGroup[group] else { return false }
        let normalized = Self.normalizedCreator(creator)
        return candidates.contains { $0.elementLow == tag & 0xFF && Self.normalizedCreator($0.creator) == normalized }
    }

    static func normalizedCreator(_ creator: String) -> String {
        creator.trimmingCharacters(in: .whitespaces).uppercased()
    }

    // MARK: - Loading

    private struct Archive: Decodable {
        struct Attribute: Decodable {
            let name: String
            let tag: String
            let basic: String
            let retired: Bool
            let inStandardIOD: Bool
            let options: [String: String]?
        }

        struct SafePrivate: Decodable {
            let element: String
            let creator: String
            let vr: String
            let vm: String
            let meaning: String
        }

        let standard: String
        let version: String
        let sourceSHA256: String
        let attributes: [Attribute]
        let safePrivateAttributes: [SafePrivate]
    }

    init(standard: String, version: String, sourceSHA256: String, entries: [Entry], safePrivateEntries: [SafePrivateEntry], privateEntry: Entry?) {
        self.standard = standard
        self.version = version
        self.sourceSHA256 = sourceSHA256
        self.entries = entries
        self.safePrivateEntries = safePrivateEntries
        self.privateEntry = privateEntry
        exact = Dictionary(uniqueKeysWithValues: entries.filter { $0.mask == 0xFFFF_FFFF }.map { ($0.value, $0) })
        patterns = entries.filter { $0.mask != 0xFFFF_FFFF }
        safeByGroup = Dictionary(grouping: safePrivateEntries, by: \.group)
    }

    static func decode(_ data: Data) throws -> DicomDeidentificationTable {
        let archive = try JSONDecoder().decode(Archive.self, from: data)
        var entries: [Entry] = []
        var privateEntry: Entry?
        for attribute in archive.attributes {
            guard let basic = ActionCode(rawValue: attribute.basic) else { throw DecodingError.dataCorrupted(.init(codingPath: [], debugDescription: "action \(attribute.basic)")) }
            var options: [Option: ActionCode] = [:]
            for (key, code) in attribute.options ?? [:] {
                guard let option = Option(rawValue: key), let action = ActionCode(rawValue: code) else {
                    throw DecodingError.dataCorrupted(.init(codingPath: [], debugDescription: "option \(key)=\(code)"))
                }
                options[option] = action
            }
            if attribute.tag == "private" {
                privateEntry = Entry(name: attribute.name, tagPattern: attribute.tag, basic: basic, options: options, retired: attribute.retired,
                                     inStandardIOD: attribute.inStandardIOD, mask: 0, value: 0)
                continue
            }
            guard attribute.tag.count == 8,
                  let mask = Int(attribute.tag.map { $0 == "x" ? "0" : "F" }.joined(), radix: 16),
                  let value = Int(attribute.tag.replacingOccurrences(of: "x", with: "0"), radix: 16) else {
                throw DecodingError.dataCorrupted(.init(codingPath: [], debugDescription: "tag \(attribute.tag)"))
            }
            entries.append(Entry(name: attribute.name, tagPattern: attribute.tag, basic: basic, options: options, retired: attribute.retired,
                                 inStandardIOD: attribute.inStandardIOD, mask: mask, value: value))
        }
        let safe = try archive.safePrivateAttributes.map { row -> SafePrivateEntry in
            guard row.element.count == 8, let group = Int(row.element.prefix(4), radix: 16), let low = Int(row.element.suffix(2), radix: 16) else {
                throw DecodingError.dataCorrupted(.init(codingPath: [], debugDescription: "safe private \(row.element)"))
            }
            return SafePrivateEntry(creator: row.creator, elementPattern: row.element, vr: row.vr, vm: row.vm, meaning: row.meaning, group: group, elementLow: low)
        }
        return DicomDeidentificationTable(standard: archive.standard, version: archive.version, sourceSHA256: archive.sourceSHA256,
                                          entries: entries, safePrivateEntries: safe, privateEntry: privateEntry)
    }

    public enum LoadError: Error, Sendable, LocalizedError {
        case resourceNotFound(bundle: String)
        case resourceReadFailed(String)
        case invalidTable(String)

        public var errorDescription: String? {
            switch self {
            case .resourceNotFound(let bundle): return "PS3.15 table lookup failed in \(bundle)"
            case .resourceReadFailed(let reason): return "PS3.15 table read failed: \(reason)"
            case .invalidTable(let reason): return "PS3.15 table decode failed: \(reason)"
            }
        }
    }

    /// Loads the packaged table while preserving whether lookup, I/O or decoding failed.
    /// The nonthrowing `standard` property remains fail-closed for existing callers.
    public static func loadStandard() throws -> DicomDeidentificationTable {
        #if SWIFT_PACKAGE
        return try load(from: Bundle.module)
        #else
        return try load(from: Bundle.main)
        #endif
    }

    static func load(from bundle: Bundle) throws -> DicomDeidentificationTable {
        guard let url = bundle.url(forResource: "DicomDeidentificationTable", withExtension: "json") else {
            throw LoadError.resourceNotFound(bundle: bundle.bundleURL.path)
        }
        return try load(at: url)
    }

    static func load(at url: URL) throws -> DicomDeidentificationTable {
        let data: Data
        do { data = try Data(contentsOf: url) }
        catch { throw LoadError.resourceReadFailed(String(describing: error)) }
        do { return try decode(data) }
        catch { throw LoadError.invalidTable(String(describing: error)) }
    }

    private static func load() -> DicomDeidentificationTable {
        do { return try loadStandard() }
        catch {
            DicomLogger.make(subsystem: "com.dicomviewer", category: "DicomDeidentification")
                .warning(error.localizedDescription)
            return DicomDeidentificationTable(standard: "PS3.15", version: "", sourceSHA256: "", entries: [], safePrivateEntries: [], privateEntry: nil)
        }
    }
}
