//
//  DicomCodecStructuredReport.swift
//  DicomCore
//
//  Canonical, PHI-free semantic record shared by codec workflow adapters.
//

import Foundation

/// Versioned PHI-free semantic report shared by codec workflow adapters.
public struct DicomCodecStructuredReport: Codable, Equatable, Sendable {
    /// Operation represented by a structured report.
    public enum Operation: String, Codable, Sendable {
        case capabilities
        case inspect
        case validate
        case decode
        case compare
        case transcode
    }

    /// Non-identifying pixel and transfer-syntax attributes of the source object.
    public struct Object: Codable, Equatable, Sendable {
        /// Source transfer syntax UID.
        public let transferSyntaxUID: String
        /// Stored image row count.
        public let rows: Int
        /// Stored image column count.
        public let columns: Int
        /// Allocated bits per sample.
        public let bitsAllocated: Int
        /// Significant stored bits per sample.
        public let bitsStored: Int
        /// DICOM pixel-representation flag, where one is signed.
        public let pixelRepresentation: Int
        /// Stored samples per pixel.
        public let samplesPerPixel: Int
        /// Stored photometric interpretation.
        public let photometricInterpretation: String
        /// Addressable frame count.
        public let frameCount: Int
        /// Whether the transfer syntax uses compressed pixel representation.
        public let compressed: Bool
        /// Whether Pixel Data uses encapsulated fragments.
        public let encapsulated: Bool
    }

    /// Codec backend identity, availability, selection, and qualified syntax record.
    public struct Backend: Codable, Equatable, Sendable {
        /// Role played by a backend in the operation.
        public enum Role: String, Codable, Sendable {
            case available
            case production
            case candidate
            case shadow
            case fallback
            case encoder
            case oracle
        }

        /// Stable backend identifier.
        public let identifier: String
        /// Backend role in this operation.
        public let role: Role
        /// Linked or runtime-reported version.
        public let version: String?
        /// Source through which the backend entered the process.
        public let source: String
        /// Whether the backend is usable in this process.
        public let available: Bool
        /// Whether this backend supplied the production output.
        public let selected: Bool
        /// Active rollout mode, when the backend is family-gated.
        public let rolloutMode: String?
        /// Stable unavailability or fallback reason.
        public let reason: String?
        /// Transfer syntax UIDs qualified for decode.
        public let decodeTransferSyntaxUIDs: [String]
        /// Transfer syntax UIDs qualified for encode.
        public let encodeTransferSyntaxUIDs: [String]
    }

    /// Non-identifying decoded-frame shape and integrity record.
    public struct Frame: Codable, Equatable, Sendable {
        /// Zero-based source frame index.
        public let index: Int
        /// Decoded frame width.
        public let width: Int
        /// Decoded frame height.
        public let height: Int
        /// Significant decoded bits per sample.
        public let bitsPerSample: Int
        /// Decoded component count.
        public let componentCount: Int
        /// Decoded pixel artifact byte count.
        public let pixelByteCount: Int
        /// Stable decoded pixel hash.
        public let pixelHash: String
    }

    /// Encapsulated Pixel Data frame-map and offset-table validation record.
    public struct Encapsulation: Codable, Equatable, Sendable {
        /// Whether the encapsulation and declared frame map are valid.
        public let valid: Bool
        /// NumberOfFrames value declared by the object.
        public let declaredFrameCount: Int
        /// Frame count safely mapped from offsets and fragments.
        public let mappedFrameCount: Int
        /// Encapsulated fragment count.
        public let fragmentCount: Int
        /// Basic Offset Table entry count.
        public let basicOffsetCount: Int
        /// Extended Offset Table entry count.
        public let extendedOffsetCount: Int
    }

    /// Generated byte artifact validation and comparison record.
    public struct Artifact: Codable, Equatable, Sendable {
        /// Media type of the generated bytes.
        public let mediaType: String
        /// Generated byte count.
        public let byteCount: Int
        /// Stable generated-content hash.
        public let contentHash: String
        /// Output transfer syntax UID for DICOM artifacts.
        public let transferSyntaxUID: String?
        /// Whether structural artifact validation passed.
        public let validationPassed: Bool
        /// Exact or semantic decoded comparison policy.
        public let comparisonMode: String?
        /// Whether decoded comparison passed when requested.
        public let comparisonPassed: Bool?
    }

    /// Stable machine-readable diagnostic emitted by a workflow operation.
    public struct Diagnostic: Codable, Equatable, Sendable {
        /// Diagnostic severity.
        public enum Severity: String, Codable, Sendable {
            case info
            case warning
            case error
        }

        /// Diagnostic severity.
        public let severity: Severity
        /// Stable diagnostic code.
        public let code: String
        /// Non-identifying diagnostic message.
        public let message: String

        /// Creates a structured diagnostic.
        public init(severity: Severity, code: String, message: String) {
            self.severity = severity
            self.code = code
            self.message = message
        }
    }

    /// Structured-report schema version.
    public let schemaVersion: Int
    /// Operation represented by this report.
    public let operation: Operation
    /// Whether the operation and requested validation succeeded.
    public let success: Bool
    /// Non-identifying source object attributes, when an object was supplied.
    public let sourceObject: Object?
    /// Destination transfer syntax UID for transcode operations.
    public let targetTransferSyntaxUID: String?
    /// Selected transcode route name.
    public let transcodeRoute: String?
    /// Backends available or involved in the operation.
    public let backends: [Backend]
    /// Decoded frame integrity records.
    public let frames: [Frame]
    /// Encapsulation validation record for encapsulated objects.
    public let encapsulation: Encapsulation?
    /// Generated artifact record, when the operation produced bytes.
    public let artifact: Artifact?
    /// Stable informational, warning, and error diagnostics.
    public let diagnostics: [Diagnostic]

    /// Creates a canonical codec workflow report.
    public init(
        schemaVersion: Int = 1,
        operation: Operation,
        success: Bool,
        sourceObject: Object? = nil,
        targetTransferSyntaxUID: String? = nil,
        transcodeRoute: String? = nil,
        backends: [Backend] = [],
        frames: [Frame] = [],
        encapsulation: Encapsulation? = nil,
        artifact: Artifact? = nil,
        diagnostics: [Diagnostic] = []
    ) {
        self.schemaVersion = schemaVersion
        self.operation = operation
        self.success = success
        self.sourceObject = sourceObject
        self.targetTransferSyntaxUID = targetTransferSyntaxUID
        self.transcodeRoute = transcodeRoute
        self.backends = backends
        self.frames = frames
        self.encapsulation = encapsulation
        self.artifact = artifact
        self.diagnostics = diagnostics
    }
}
