// dcmj2knhe_encode_block_ht.c — custom C+NEON tier-1 HT block encoder.
//
// v9.4-research scope: scalar baseline (no NEON yet). Mirrors
// HTBlockEncoderConformant.encodeLoopGeneric in J2KSwift's Swift
// codebase line-for-line, producing bit-exact byte-equivalent output.
// NEON tuning lands in a follow-up commit after the scalar version
// passes the V94NEONHotPathParityTests 500-trial sweep.
//
// Bit-exact correctness gate: V94NEONHotPathParityTests in
// Tests/J2KCodecTests/. Tables are sourced from dcmj2knhe_tables.c (which
// was generated by dumping the Swift conformant tables — bit-identity
// gated by testTablesMatchSwiftSourceOfTruth).

#include "j2knhe.h"
#include "j2knhe_tables.h"

#include <stdint.h>
#include <stddef.h>
#include <string.h>

// Architecture detection. Only ARM64 will pull in NEON intrinsics; on
// other targets we fall back to a portable scalar implementation. v9.4-
// research only ships on Apple Silicon so NEON is the expected path.
#if defined(__ARM_NEON) || defined(__aarch64__)
#define J2KNHE_HAS_NEON 1
#include <arm_neon.h>
#else
#define J2KNHE_HAS_NEON 0
#endif

#if J2KNHE_HAS_NEON
static const char kVersion[] = "dcmj2knhe-v9.4-research-neon";
#else
static const char kVersion[] = "dcmj2knhe-v9.4-research-scalar";
#endif

const char *dcmj2knhe_version(void) {
    return kVersion;
}

// MARK: - MagSgn engine (forward bit stream, MSB-stuff at 0xFF)

typedef struct {
    uint8_t *buf;
    size_t   cap;
    size_t   len;
    uint32_t tmp;       // partial-byte accumulator, LSB-first
    int      usedBits;
    int      maxBits;   // 7 after stuffing, 8 otherwise
    int      overflow;
} dcmj2knhe_magsgn;

static inline void magsgn_init(dcmj2knhe_magsgn *s, uint8_t *buf, size_t cap) {
    s->buf = buf;
    s->cap = cap;
    s->len = 0;
    s->tmp = 0;
    s->usedBits = 0;
    s->maxBits = 8;
    s->overflow = 0;
}

static inline void magsgn_append_byte(dcmj2knhe_magsgn *s, uint8_t byte) {
    if (s->len >= s->cap) { s->overflow = 1; return; }
    s->buf[s->len++] = byte;
    s->maxBits = (byte == 0xFF) ? 7 : 8;
    s->tmp = 0;
    s->usedBits = 0;
}

// Mirror of HTMagSgnEncoderConformant.encode(codeword:count:) including
// the v9.2 Phase 2a fast-path (count fits in current byte) and the
// while-loop slow-path.
static inline void magsgn_encode(dcmj2knhe_magsgn *s, uint32_t codeword, int count) {
    int avail = s->maxBits - s->usedBits;
    if (count > 0 && count < avail) {
        uint32_t mask = (uint32_t)1 << count;
        mask -= 1;
        s->tmp |= (codeword & mask) << s->usedBits;
        s->usedBits += count;
        return;
    }
    uint32_t cwd = codeword;
    int len = count;
    while (len > 0) {
        int take_room = s->maxBits - s->usedBits;
        int take = (take_room < len) ? take_room : len;
        uint32_t mask = (take >= 32) ? ~(uint32_t)0 : (((uint32_t)1 << take) - 1);
        s->tmp |= (cwd & mask) << s->usedBits;
        s->usedBits += take;
        cwd >>= take;
        len -= take;
        if (s->usedBits >= s->maxBits) {
            uint8_t byte = (uint8_t)(s->tmp & 0xFF);
            magsgn_append_byte(s, byte);
        }
    }
}

// Mirror of HTMagSgnEncoderConformant.encode64(codeword:count:) — the
// v9.3 Path B Phase 3 batched 4-sample emit primitive.
static inline void magsgn_encode64(dcmj2knhe_magsgn *s, uint64_t codeword, int count) {
    if (count == 0) return;
    int avail = s->maxBits - s->usedBits;
    if (count < avail) {
        uint64_t mask = ((uint64_t)1 << count) - 1;
        s->tmp |= (uint32_t)(codeword & mask) << s->usedBits;
        s->usedBits += count;
        return;
    }
    uint64_t cwd64 = codeword;
    int len = count;
    while (len > 32) {
        int take = s->maxBits - s->usedBits;
        uint64_t mask = ((uint64_t)1 << take) - 1;
        s->tmp |= (uint32_t)(cwd64 & mask) << s->usedBits;
        s->usedBits += take;
        cwd64 >>= take;
        len -= take;
        if (s->usedBits >= s->maxBits) {
            uint8_t byte = (uint8_t)(s->tmp & 0xFF);
            magsgn_append_byte(s, byte);
        }
    }
    uint32_t cwd = (uint32_t)(cwd64 & 0xFFFFFFFFu);
    // Loop tail equivalent to magsgn_encode body with `cwd` + `len`.
    while (len > 0) {
        int take_room = s->maxBits - s->usedBits;
        int take = (take_room < len) ? take_room : len;
        uint32_t mask = (take >= 32) ? ~(uint32_t)0 : (((uint32_t)1 << take) - 1);
        s->tmp |= (cwd & mask) << s->usedBits;
        s->usedBits += take;
        cwd >>= take;
        len -= take;
        if (s->usedBits >= s->maxBits) {
            uint8_t byte = (uint8_t)(s->tmp & 0xFF);
            magsgn_append_byte(s, byte);
        }
    }
}

// Mirror of HTMagSgnEncoderConformant.finish() — flushes final partial
// byte, drops 0xFF padding, rolls back over-committed stuff-slot.
static inline void magsgn_finish(dcmj2knhe_magsgn *s) {
    if (s->usedBits != 0) {
        int padBits = s->maxBits - s->usedBits;
        uint32_t padMask = (padBits >= 32) ? ~(uint32_t)0
                                           : (((uint32_t)1 << padBits) - 1);
        s->tmp |= padMask << s->usedBits;
        uint8_t byte = (uint8_t)(s->tmp & 0xFF);
        if (byte != 0xFF) {
            if (s->len >= s->cap) { s->overflow = 1; return; }
            s->buf[s->len++] = byte;
        }
        s->tmp = 0;
        s->usedBits = 0;
        s->maxBits = 8;
    } else if (s->maxBits == 7) {
        // Rollback over-committed byte slot — terminate convention.
        if (s->len > 0) s->len--;
        s->maxBits = 8;
    }
}

// MARK: - Forward bit emitter (MEL underlying)
//
// Mirrors HTForwardBitEmitterConformant — bits packed MSB-first into
// bytes (high-order bit of each byte is written first). FF-stuffing on
// 0xFF emit. Used internally by the MEL encoder.

typedef struct {
    uint8_t *buf;
    size_t   cap;
    size_t   len;
    int      tmp;
    int      remainingBits;
    int      overflow;
} dcmj2knhe_fwd_bits;

static inline void fwd_bits_init(dcmj2knhe_fwd_bits *e, uint8_t *buf, size_t cap) {
    e->buf = buf;
    e->cap = cap;
    e->len = 0;
    e->tmp = 0;
    e->remainingBits = 8;
    e->overflow = 0;
}

static inline void fwd_bits_emit(dcmj2knhe_fwd_bits *e, int bit) {
    e->tmp = (e->tmp << 1) | (bit & 1);
    e->remainingBits -= 1;
    if (e->remainingBits == 0) {
        uint8_t byte = (uint8_t)(e->tmp & 0xFF);
        if (e->len >= e->cap) { e->overflow = 1; return; }
        e->buf[e->len++] = byte;
        e->remainingBits = (byte == 0xFF) ? 7 : 8;
        e->tmp = 0;
    }
}

static inline void fwd_bits_finish(dcmj2knhe_fwd_bits *e) {
    if (e->remainingBits != 8) {
        int shift = e->remainingBits;
        e->tmp <<= shift;
        if (e->len >= e->cap) { e->overflow = 1; return; }
        e->buf[e->len++] = (uint8_t)(e->tmp & 0xFF);
        e->tmp = 0;
        e->remainingBits = 8;
    }
}

// MARK: - MEL engine
//
// MEL state table from Swift's melExpConformant. Threshold at state k
// is `1 << melExp[k]`. State 12 caps out at 5 (threshold 32).
static const int kMelExp[13] = { 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 4, 5 };

typedef struct {
    dcmj2knhe_fwd_bits emitter;
    int             state;
    int             run;
    int             threshold;
} dcmj2knhe_mel;

static inline void mel_init(dcmj2knhe_mel *m, uint8_t *buf, size_t cap) {
    fwd_bits_init(&m->emitter, buf, cap);
    m->state = 0;
    m->run = 0;
    m->threshold = 1 << kMelExp[0];
}

// Mirror of HTMELEncoderConformant.encode(eventIsOne:).
static inline void mel_encode_event(dcmj2knhe_mel *m, int event_is_one) {
    if (!event_is_one) {
        m->run += 1;
        if (m->run >= m->threshold) {
            fwd_bits_emit(&m->emitter, 1);
            m->run = 0;
            m->state = (m->state + 1) < 12 ? (m->state + 1) : 12;
            m->threshold = 1 << kMelExp[m->state];
        }
    } else {
        fwd_bits_emit(&m->emitter, 0);
        int t = kMelExp[m->state];
        while (t > 0) {
            t -= 1;
            fwd_bits_emit(&m->emitter, (m->run >> t) & 1);
        }
        m->run = 0;
        m->state = (m->state - 1) > 0 ? (m->state - 1) : 0;
        m->threshold = 1 << kMelExp[m->state];
    }
}

// Mirror of HTMELEncoderConformant.finish() — emit a final `1` bit if a
// non-terminated zero run is still open, then flush the partial byte.
static inline void mel_finish(dcmj2knhe_mel *m) {
    if (m->run > 0) {
        fwd_bits_emit(&m->emitter, 1);
    }
    fwd_bits_finish(&m->emitter);
}

// MARK: - VLC reverse-bit emitter
//
// Mirrors HTReverseBitEmitterConformant. Bytes are written into the
// scratch in `emittedReversed` order (sentinel-first), then on finish
// reversed into the caller's vlc buffer for forward on-wire output.
// Max VLC size for a 64×64 block is bounded but conservative: we use a
// 4 KB stack-resident scratch (Part-15 caps scup at 4079).

#define J2KNHE_VLC_SCRATCH_BYTES 4096

typedef struct {
    uint8_t reversed[J2KNHE_VLC_SCRATCH_BYTES];
    int     idx;
    int     tmp;
    int     usedBits;
    int     lastGreaterThan8F;
    int     overflow;
} dcmj2knhe_vlc;

static inline void vlc_init(dcmj2knhe_vlc *v) {
    v->reversed[0] = 0xFF;  // sentinel
    v->idx = 1;
    v->tmp = 0x0F;
    v->usedBits = 4;
    v->lastGreaterThan8F = 1;  // sentinel is > 0x8F
    v->overflow = 0;
}

// Mirror of HTReverseBitEmitterConformant.encode(codeword:count:).
static inline void vlc_encode(dcmj2knhe_vlc *v, int codeword, int count) {
    int cwd = codeword;
    int len = count;
    while (len > 0) {
        int stuffPenalty = v->lastGreaterThan8F ? 1 : 0;
        int availBits = 8 - stuffPenalty - v->usedBits;
        int take = (availBits < len) ? availBits : len;
        if (take > 0) {
            int mask = (1 << take) - 1;
            v->tmp |= (cwd & mask) << v->usedBits;
            v->usedBits += take;
            cwd >>= take;
            len -= take;
        }
        int remainingAfter = availBits - take;
        if (remainingAfter == 0) {
            if (v->lastGreaterThan8F && v->tmp != 0x7F) {
                // Stuff-bit only; no real byte emission yet.
                v->lastGreaterThan8F = 0;
                continue;
            }
            if (v->idx >= J2KNHE_VLC_SCRATCH_BYTES) {
                v->overflow = 1;
                return;
            }
            v->reversed[v->idx++] = (uint8_t)(v->tmp & 0xFF);
            v->lastGreaterThan8F = (v->tmp > 0x8F) ? 1 : 0;
            v->tmp = 0;
            v->usedBits = 0;
        }
    }
}

// Mirror of HTReverseBitEmitterConformant.finish() — flush partial byte
// into emittedReversed, then reverse-copy into caller's buffer.
static inline int vlc_finish(dcmj2knhe_vlc *v, uint8_t *out_buf, size_t out_cap,
                              size_t *out_len)
{
    if (v->usedBits > 0) {
        if (v->idx >= J2KNHE_VLC_SCRATCH_BYTES) {
            v->overflow = 1;
            return -1;
        }
        v->reversed[v->idx++] = (uint8_t)(v->tmp & 0xFF);
        v->tmp = 0;
        v->usedBits = 0;
    }
    if (v->overflow) return -1;
    size_t n = (size_t)v->idx;
    if (n > out_cap) return -1;
    // Reverse-copy: reversed[0..n-1] -> out_buf[n-1..0]
    for (size_t i = 0; i < n; i++) {
        out_buf[n - 1 - i] = v->reversed[i];
    }
    *out_len = n;
    return 0;
}

// MARK: - processQuad
//
// Per-sample classifier + 4-sample quad assembly. Mirrors Swift's
// `sampleInfo` + `processQuad` scalar path. Returns a packed struct so
// the compiler can keep these in registers (matching the Swift tuple
// return convention).

typedef struct {
    int      rho;
    int      eQMax;
    int      eQ[4];
    uint32_t s[4];
} dcmj2knhe_quad;

// Sample classifier — mirrors Swift sampleInfo.
// `t` is the input UInt32 (bit 31 = sign, bits 0..(30-p) = magnitude).
// `p` is `30 - missingMSBs` cached by the caller.
static inline void sample_info(uint32_t t, uint32_t p,
                                int *out_sig, int *out_eQ, uint32_t *out_payload)
{
    uint32_t val = (t + t) >> p;
    val &= ~(uint32_t)1;
    if (val == 0) {
        *out_sig = 0;
        *out_eQ = 0;
        *out_payload = 0;
        return;
    }
    val -= 1;
    int lz = __builtin_clz(val);
    int eQ = 32 - lz;
    uint32_t sign = (t >> 31) & 1;
    uint32_t payload = (val - 1) + sign;
    *out_sig = 1;
    *out_eQ = eQ;
    *out_payload = payload;
}

static inline void process_quad(const uint32_t *coef_base,
                                 int baseX, int baseY,
                                 int width, int height,
                                 uint32_t p,
                                 dcmj2knhe_quad *q)
{
#if J2KNHE_HAS_NEON
    // v9.4-research Day 6a — NEON 4-lane classifier. Replaces the
    // 4× scalar sample_info calls with a single SIMD4 sequence using
    // the key intrinsic Swift cannot access: vclzq_u32 (lane-wise
    // count-leading-zeros). Bit-exact equivalent of the scalar path
    // (verified by V94NEONHotPathParityTests 500-trial sweep + 37
    // existing bit-exact gates including HTCrossCodecConformantTests
    // byte-identity vs OpenJPH/OpenJPEG/Kakadu).
    //
    // Lane layout matches Swift processQuad / sample_info:
    //   lane 0: (baseX,     baseY)
    //   lane 1: (baseX,     baseY + 1)
    //   lane 2: (baseX + 1, baseY)
    //   lane 3: (baseX + 1, baseY + 1)
    // Boundary samples that fall outside the block (baseX+1 >= width
    // or baseY+1 >= height) are read as 0, matching Swift's fetch
    // semantics for out-of-bounds positions.

    uint32_t t0 = (baseX < width && baseY < height)
        ? coef_base[baseY * width + baseX] : 0u;
    uint32_t t1 = (baseX < width && (baseY + 1) < height)
        ? coef_base[(baseY + 1) * width + baseX] : 0u;
    uint32_t t2 = ((baseX + 1) < width && baseY < height)
        ? coef_base[baseY * width + (baseX + 1)] : 0u;
    uint32_t t3 = ((baseX + 1) < width && (baseY + 1) < height)
        ? coef_base[(baseY + 1) * width + (baseX + 1)] : 0u;

    uint32_t lanes[4] = { t0, t1, t2, t3 };
    uint32x4_t t = vld1q_u32(lanes);

    // val = ((t + t) >> p) & ~1u  — SIMD4 lane-parallel
    uint32x4_t shifted = vshlq_n_u32(t, 1);                    // t + t (= t << 1)
    int32x4_t shift_right = vdupq_n_s32(-(int32_t)p);          // shift_right by p
    uint32x4_t val = vshlq_u32(shifted, shift_right);          // >> p
    val = vbicq_u32(val, vdupq_n_u32(1));                       // & ~1

    // sig_mask: lane = 0xFFFFFFFF if val != 0, else 0
    uint32x4_t is_zero = vceqzq_u32(val);
    uint32x4_t sig_mask = vmvnq_u32(is_zero);

    // valMinus1 = val - 1 (for sig lanes; for non-sig lanes this is
    // 0xFFFFFFFF, but the sig_mask zeros it out later).
    uint32x4_t valMinus1 = vsubq_u32(val, vdupq_n_u32(1));

    // For NON-sig lanes, valMinus1 = -1 = 0xFFFFFFFF. vclzq_u32(0xFFFFFFFF) = 0
    // so eQ = 32 - 0 = 32 for non-sig. We mask out eQ via sig_mask.
    // For SIG lanes, vclzq_u32(val-1) gives a count in [0, 31]; eQ = 32 - lz
    // is in [1, 32].
    uint32x4_t lz = vclzq_u32(valMinus1);
    int32x4_t eQ = vsubq_s32(vdupq_n_s32(32), vreinterpretq_s32_u32(lz));
    // Mask non-sig lanes to eQ=0.
    int32x4_t eQ_masked = vandq_s32(eQ, vreinterpretq_s32_u32(sig_mask));

    // sign = (t >> 31) & 1
    uint32x4_t sign = vshrq_n_u32(t, 31);

    // payload = (valMinus1 - 1) + sign — for non-sig, valMinus1-1 = -2,
    // so payload is junk; the sig_mask zeros it.
    uint32x4_t payload = vaddq_u32(vsubq_u32(valMinus1, vdupq_n_u32(1)), sign);
    uint32x4_t payload_masked = vandq_u32(payload, sig_mask);

    // Extract lanes back to scalar tuple. Compiler should keep these
    // in registers; gcc/clang ARM64 typically uses umov for these.
    uint32_t sm0 = vgetq_lane_u32(sig_mask, 0);
    uint32_t sm1 = vgetq_lane_u32(sig_mask, 1);
    uint32_t sm2 = vgetq_lane_u32(sig_mask, 2);
    uint32_t sm3 = vgetq_lane_u32(sig_mask, 3);

    q->rho = 0;
    q->eQMax = 0;
    q->eQ[0] = (int)vgetq_lane_s32(eQ_masked, 0);
    q->eQ[1] = (int)vgetq_lane_s32(eQ_masked, 1);
    q->eQ[2] = (int)vgetq_lane_s32(eQ_masked, 2);
    q->eQ[3] = (int)vgetq_lane_s32(eQ_masked, 3);
    q->s[0] = vgetq_lane_u32(payload_masked, 0);
    q->s[1] = vgetq_lane_u32(payload_masked, 1);
    q->s[2] = vgetq_lane_u32(payload_masked, 2);
    q->s[3] = vgetq_lane_u32(payload_masked, 3);

    if (sm0) { q->rho |= 1; if (q->eQ[0] > q->eQMax) q->eQMax = q->eQ[0]; }
    if (sm1) { q->rho |= 2; if (q->eQ[1] > q->eQMax) q->eQMax = q->eQ[1]; }
    if (sm2) { q->rho |= 4; if (q->eQ[2] > q->eQMax) q->eQMax = q->eQ[2]; }
    if (sm3) { q->rho |= 8; if (q->eQ[3] > q->eQMax) q->eQMax = q->eQ[3]; }

#else  // scalar fallback for non-NEON builds

    q->rho = 0;
    q->eQMax = 0;
    q->eQ[0] = q->eQ[1] = q->eQ[2] = q->eQ[3] = 0;
    q->s[0] = q->s[1] = q->s[2] = q->s[3] = 0;

    int sig; int eQ; uint32_t payload;
    if (baseX < width && baseY < height) {
        sample_info(coef_base[baseY * width + baseX], p, &sig, &eQ, &payload);
        if (sig) {
            q->rho |= 1;
            q->eQ[0] = eQ;
            q->s[0] = payload;
            if (eQ > q->eQMax) q->eQMax = eQ;
        }
    }
    if (baseX < width && (baseY + 1) < height) {
        sample_info(coef_base[(baseY + 1) * width + baseX], p, &sig, &eQ, &payload);
        if (sig) {
            q->rho |= 2;
            q->eQ[1] = eQ;
            q->s[1] = payload;
            if (eQ > q->eQMax) q->eQMax = eQ;
        }
    }
    if ((baseX + 1) < width && baseY < height) {
        sample_info(coef_base[baseY * width + (baseX + 1)], p, &sig, &eQ, &payload);
        if (sig) {
            q->rho |= 4;
            q->eQ[2] = eQ;
            q->s[2] = payload;
            if (eQ > q->eQMax) q->eQMax = eQ;
        }
    }
    if ((baseX + 1) < width && (baseY + 1) < height) {
        sample_info(coef_base[(baseY + 1) * width + (baseX + 1)], p, &sig, &eQ, &payload);
        if (sig) {
            q->rho |= 8;
            q->eQ[3] = eQ;
            q->s[3] = payload;
            if (eQ > q->eQMax) q->eQMax = eQ;
        }
    }

#endif  // J2KNHE_HAS_NEON
}

// MARK: - emitQuadMagSgn
//
// Mirrors Swift v9.3 emitQuadMagSgn — batched 4-sample MagSgn emit for
// Uq ≤ 16 (combined UInt64 in one encode64 call); legacy per-sample for
// Uq > 16. rho == 0 fast-skip.

static inline void emit_quad_magsgn(dcmj2knhe_magsgn *ms,
                                     int rho, int tuple, int Uq,
                                     uint32_t s0, uint32_t s1,
                                     uint32_t s2, uint32_t s3)
{
    if (rho == 0) return;
    if (Uq <= 16) {
        uint64_t combined = 0;
        int totalBits = 0;
        if (rho & 1) {
            int m = Uq - (tuple & 1);
            uint32_t mask = ((uint32_t)1 << m) - 1;
            combined |= (uint64_t)(s0 & mask) << totalBits;
            totalBits += m;
        }
        if (rho & 2) {
            int m = Uq - ((tuple >> 1) & 1);
            uint32_t mask = ((uint32_t)1 << m) - 1;
            combined |= (uint64_t)(s1 & mask) << totalBits;
            totalBits += m;
        }
        if (rho & 4) {
            int m = Uq - ((tuple >> 2) & 1);
            uint32_t mask = ((uint32_t)1 << m) - 1;
            combined |= (uint64_t)(s2 & mask) << totalBits;
            totalBits += m;
        }
        if (rho & 8) {
            int m = Uq - ((tuple >> 3) & 1);
            uint32_t mask = ((uint32_t)1 << m) - 1;
            combined |= (uint64_t)(s3 & mask) << totalBits;
            totalBits += m;
        }
        magsgn_encode64(ms, combined, totalBits);
        return;
    }
    // Uq > 16 fallback: per-sample emit.
    if (rho & 1) {
        int m = Uq - (tuple & 1);
        uint32_t mask = (m >= 32) ? ~(uint32_t)0 : (((uint32_t)1 << m) - 1);
        magsgn_encode(ms, s0 & mask, m);
    }
    if (rho & 2) {
        int m = Uq - ((tuple >> 1) & 1);
        uint32_t mask = (m >= 32) ? ~(uint32_t)0 : (((uint32_t)1 << m) - 1);
        magsgn_encode(ms, s1 & mask, m);
    }
    if (rho & 4) {
        int m = Uq - ((tuple >> 2) & 1);
        uint32_t mask = (m >= 32) ? ~(uint32_t)0 : (((uint32_t)1 << m) - 1);
        magsgn_encode(ms, s2 & mask, m);
    }
    if (rho & 8) {
        int m = Uq - ((tuple >> 3) & 1);
        uint32_t mask = (m >= 32) ? ~(uint32_t)0 : (((uint32_t)1 << m) - 1);
        magsgn_encode(ms, s3 & mask, m);
    }
}

// Helpers to unpack UVLC table entries.
// Layout per dcmj2knhe_tables.h: bits 0..7 = pre, 8..15 = preLen,
//                              16..23 = suf, 24..31 = sufLen.
static inline int uvlc_pre(uint32_t e)    { return (int)(e & 0xFF); }
static inline int uvlc_preLen(uint32_t e) { return (int)((e >> 8) & 0xFF); }
static inline int uvlc_suf(uint32_t e)    { return (int)((e >> 16) & 0xFF); }
static inline int uvlc_sufLen(uint32_t e) { return (int)((e >> 24) & 0xFF); }

// MARK: - Main entry point

int dcmj2knhe_encode_block_ht32(
    const uint32_t *coefficients,
    uint32_t width_u, uint32_t height_u,
    uint32_t missing_msbs,
    uint8_t *magsgn_buf, size_t magsgn_cap, size_t *magsgn_len,
    uint8_t *mel_buf,    size_t mel_cap,    size_t *mel_len,
    uint8_t *vlc_buf,    size_t vlc_cap,    size_t *vlc_len)
{
    if (width_u == 0 || width_u > 64 || height_u == 0 || height_u > 64)
        return -2;
    if (missing_msbs >= 30) return -2;
    if (coefficients == NULL) return -2;

    const int width  = (int)width_u;
    const int height = (int)height_u;
    const uint32_t p = 30u - missing_msbs;

    // Stack-allocated scratch — mirrors v9.2 Phase 0b withUnsafeTemporary-
    // Allocation. guardedWidth = ((width+3)/4)*2 + 2; <= 34 for w=64.
    const int guardedWidth = ((width + 3) / 4) * 2 + 2;
    uint8_t eVal[34];
    uint8_t cxVal[34];
    memset(eVal, 0, sizeof(eVal));
    memset(cxVal, 0, sizeof(cxVal));

    dcmj2knhe_magsgn ms; magsgn_init(&ms, magsgn_buf, magsgn_cap);
    dcmj2knhe_mel    me; mel_init(&me, mel_buf, mel_cap);
    dcmj2knhe_vlc    vl; vlc_init(&vl);

    // --- Initial row of quads (y = 0, 1) ---
    int c_q0 = 0;
    int lep = 0;
    int lcxp = 0;
    eVal[lep] = 0;
    cxVal[lcxp] = 0;

    if (height > 0) {
        int spX = 0;
        while (spX < width) {
            dcmj2knhe_quad q0;
            process_quad(coefficients, spX, 0, width, height, p, &q0);
            int rho0 = q0.rho;
            int eQMax0 = q0.eQMax;
            int Uq0 = (eQMax0 > 1) ? eQMax0 : 1;
            int u_q0 = Uq0 - 1;
            int eps0 = 0;
            if (u_q0 > 0) {
                if (q0.eQ[0] == eQMax0) eps0 |= 1;
                if (q0.eQ[1] == eQMax0) eps0 |= 2;
                if (q0.eQ[2] == eQMax0) eps0 |= 4;
                if (q0.eQ[3] == eQMax0) eps0 |= 8;
            }
            // lep / lcxp bookkeeping
            if ((uint8_t)q0.eQ[1] > eVal[lep]) eVal[lep] = (uint8_t)q0.eQ[1];
            lep += 1;
            eVal[lep] = (uint8_t)q0.eQ[3];
            cxVal[lcxp] = cxVal[lcxp] | (uint8_t)((rho0 & 2) >> 1);
            lcxp += 1;
            cxVal[lcxp] = (uint8_t)((rho0 & 8) >> 3);

            int tuple0 = (int)dcmj2knhe_vlc_table0[(c_q0 << 8) | (rho0 << 4) | eps0];
            vlc_encode(&vl, tuple0 >> 8, (tuple0 >> 4) & 0x7);

            if (c_q0 == 0) {
                mel_encode_event(&me, rho0 != 0);
            }

            emit_quad_magsgn(&ms, rho0, tuple0, Uq0,
                              q0.s[0], q0.s[1], q0.s[2], q0.s[3]);

            // Second quad of pair
            int rho1 = 0, u_q1 = 0;
            if (spX + 2 < width) {
                dcmj2knhe_quad q1;
                process_quad(coefficients, spX + 2, 0, width, height, p, &q1);
                int eQMax1 = q1.eQMax;
                rho1 = q1.rho;
                int c_q1 = (rho0 >> 1) | (rho0 & 1);
                int Uq1 = (eQMax1 > 1) ? eQMax1 : 1;
                u_q1 = Uq1 - 1;
                int eps1 = 0;
                if (u_q1 > 0) {
                    if (q1.eQ[0] == eQMax1) eps1 |= 1;
                    if (q1.eQ[1] == eQMax1) eps1 |= 2;
                    if (q1.eQ[2] == eQMax1) eps1 |= 4;
                    if (q1.eQ[3] == eQMax1) eps1 |= 8;
                }
                if ((uint8_t)q1.eQ[1] > eVal[lep]) eVal[lep] = (uint8_t)q1.eQ[1];
                lep += 1;
                eVal[lep] = (uint8_t)q1.eQ[3];
                cxVal[lcxp] = cxVal[lcxp] | (uint8_t)((rho1 & 2) >> 1);
                lcxp += 1;
                cxVal[lcxp] = (uint8_t)((rho1 & 8) >> 3);

                int tuple1 = (int)dcmj2knhe_vlc_table0[(c_q1 << 8) | (rho1 << 4) | eps1];
                vlc_encode(&vl, tuple1 >> 8, (tuple1 >> 4) & 0x7);

                if (c_q1 == 0) {
                    mel_encode_event(&me, rho1 != 0);
                }

                emit_quad_magsgn(&ms, rho1, tuple1, Uq1,
                                  q1.s[0], q1.s[1], q1.s[2], q1.s[3]);
            }

            // U-value encoding for this quad pair (first row only — uses
            // kappa = 1, encoding `u_q = Uq - 1`).
            if (u_q0 > 0 && u_q1 > 0) {
                mel_encode_event(&me, ((u_q0 < u_q1 ? u_q0 : u_q1) > 2) ? 1 : 0);
            }
            if (u_q0 > 2 && u_q1 > 2) {
                uint32_t e0 = dcmj2knhe_uvlc_table[u_q0 - 2];
                uint32_t e1 = dcmj2knhe_uvlc_table[u_q1 - 2];
                vlc_encode(&vl, uvlc_pre(e0), uvlc_preLen(e0));
                vlc_encode(&vl, uvlc_pre(e1), uvlc_preLen(e1));
                vlc_encode(&vl, uvlc_suf(e0), uvlc_sufLen(e0));
                vlc_encode(&vl, uvlc_suf(e1), uvlc_sufLen(e1));
            } else if (u_q0 > 2 && u_q1 > 0) {
                uint32_t e0 = dcmj2knhe_uvlc_table[u_q0];
                vlc_encode(&vl, uvlc_pre(e0), uvlc_preLen(e0));
                vlc_encode(&vl, u_q1 - 1, 1);
                vlc_encode(&vl, uvlc_suf(e0), uvlc_sufLen(e0));
            } else {
                uint32_t e0 = dcmj2knhe_uvlc_table[u_q0];
                uint32_t e1 = dcmj2knhe_uvlc_table[u_q1];
                vlc_encode(&vl, uvlc_pre(e0), uvlc_preLen(e0));
                vlc_encode(&vl, uvlc_pre(e1), uvlc_preLen(e1));
                vlc_encode(&vl, uvlc_suf(e0), uvlc_sufLen(e0));
                vlc_encode(&vl, uvlc_suf(e1), uvlc_sufLen(e1));
            }

            c_q0 = (rho1 >> 1) | (rho1 & 1);
            spX += 4;
        }
    }
    // End-of-row sentinel.
    if (lep + 1 < guardedWidth) {
        eVal[lep + 1] = 0;
    }

    // --- Subsequent quad rows (y = 2, 4, ...) ---
    for (int y = 2; y < height; y += 2) {
        lep = 0;
        int maxE = ((int)eVal[0] > (int)eVal[1] ? (int)eVal[0] : (int)eVal[1]) - 1;
        eVal[0] = 0;
        lcxp = 0;
        c_q0 = (int)cxVal[0] + ((int)cxVal[1] << 2);
        cxVal[0] = 0;

        int spX = 0;
        while (spX < width) {
            dcmj2knhe_quad q0;
            process_quad(coefficients, spX, y, width, height, p, &q0);
            int rho0 = q0.rho;
            int eQMax0 = q0.eQMax;
            // kappaA = (rho0 has >1 bit set) ? max(1, maxE) : 1
            int kappaA = ((rho0 & (rho0 - 1)) != 0)
                ? ((1 > maxE) ? 1 : maxE)
                : 1;
            int Uq0 = (eQMax0 > kappaA) ? eQMax0 : kappaA;
            int u_q0 = Uq0 - kappaA;
            int eps0 = 0;
            if (u_q0 > 0) {
                if (q0.eQ[0] == eQMax0) eps0 |= 1;
                if (q0.eQ[1] == eQMax0) eps0 |= 2;
                if (q0.eQ[2] == eQMax0) eps0 |= 4;
                if (q0.eQ[3] == eQMax0) eps0 |= 8;
            }
            if ((uint8_t)q0.eQ[1] > eVal[lep]) eVal[lep] = (uint8_t)q0.eQ[1];
            lep += 1;
            maxE = ((int)eVal[lep] > (int)eVal[lep + 1] ? (int)eVal[lep] : (int)eVal[lep + 1]) - 1;
            eVal[lep] = (uint8_t)q0.eQ[3];
            cxVal[lcxp] = cxVal[lcxp] | (uint8_t)((rho0 & 2) >> 1);
            lcxp += 1;
            int c_q1 = (int)cxVal[lcxp] + ((int)cxVal[lcxp + 1] << 2);
            cxVal[lcxp] = (uint8_t)((rho0 & 8) >> 3);

            int tuple0 = (int)dcmj2knhe_vlc_table1[(c_q0 << 8) | (rho0 << 4) | eps0];
            vlc_encode(&vl, tuple0 >> 8, (tuple0 >> 4) & 0x7);
            if (c_q0 == 0) {
                mel_encode_event(&me, rho0 != 0);
            }
            emit_quad_magsgn(&ms, rho0, tuple0, Uq0,
                              q0.s[0], q0.s[1], q0.s[2], q0.s[3]);

            int rho1 = 0, u_q1 = 0;
            if (spX + 2 < width) {
                dcmj2knhe_quad q1;
                process_quad(coefficients, spX + 2, y, width, height, p, &q1);
                int eQMax1 = q1.eQMax;
                rho1 = q1.rho;
                int kappaB = ((rho1 & (rho1 - 1)) != 0)
                    ? ((1 > maxE) ? 1 : maxE)
                    : 1;
                c_q1 |= ((rho0 & 4) >> 1) | ((rho0 & 8) >> 2);
                int Uq1 = (eQMax1 > kappaB) ? eQMax1 : kappaB;
                u_q1 = Uq1 - kappaB;
                int eps1 = 0;
                if (u_q1 > 0) {
                    if (q1.eQ[0] == eQMax1) eps1 |= 1;
                    if (q1.eQ[1] == eQMax1) eps1 |= 2;
                    if (q1.eQ[2] == eQMax1) eps1 |= 4;
                    if (q1.eQ[3] == eQMax1) eps1 |= 8;
                }
                if ((uint8_t)q1.eQ[1] > eVal[lep]) eVal[lep] = (uint8_t)q1.eQ[1];
                lep += 1;
                maxE = ((int)eVal[lep] > (int)eVal[lep + 1] ? (int)eVal[lep] : (int)eVal[lep + 1]) - 1;
                eVal[lep] = (uint8_t)q1.eQ[3];
                cxVal[lcxp] = cxVal[lcxp] | (uint8_t)((rho1 & 2) >> 1);
                lcxp += 1;
                c_q0 = (int)cxVal[lcxp] + ((int)cxVal[lcxp + 1] << 2);
                cxVal[lcxp] = (uint8_t)((rho1 & 8) >> 3);

                int tuple1 = (int)dcmj2knhe_vlc_table1[(c_q1 << 8) | (rho1 << 4) | eps1];
                vlc_encode(&vl, tuple1 >> 8, (tuple1 >> 4) & 0x7);
                if (c_q1 == 0) {
                    mel_encode_event(&me, rho1 != 0);
                }
                emit_quad_magsgn(&ms, rho1, tuple1, Uq1,
                                  q1.s[0], q1.s[1], q1.s[2], q1.s[3]);
            }

            // Subsequent rows use unconditional UVLC per quad.
            uint32_t e0 = dcmj2knhe_uvlc_table[u_q0];
            uint32_t e1 = dcmj2knhe_uvlc_table[u_q1];
            vlc_encode(&vl, uvlc_pre(e0), uvlc_preLen(e0));
            vlc_encode(&vl, uvlc_pre(e1), uvlc_preLen(e1));
            vlc_encode(&vl, uvlc_suf(e0), uvlc_sufLen(e0));
            vlc_encode(&vl, uvlc_suf(e1), uvlc_sufLen(e1));

            c_q0 |= ((rho1 & 4) >> 1) | ((rho1 & 8) >> 2);
            spX += 4;
        }
    }

    // Finalize all three engines.
    magsgn_finish(&ms);
    mel_finish(&me);
    if (ms.overflow || me.emitter.overflow) return -1;

    *magsgn_len = ms.len;
    *mel_len    = me.emitter.len;

    if (vlc_finish(&vl, vlc_buf, vlc_cap, vlc_len) != 0) {
        return -1;
    }
    return 0;
}
